services:
  mongo_db:
    container_name: database_container
    image: mongo:latest
    restart: always
    volumes:
      - mongo_db:/data/db
  server:
    build:
      context: .
    environment:
      NODE_ENV: production
      DATABASE_URL: mongodb://mongo_db:27017/short-url
      PORT: 8080
    depends_on:
      - mongo_db 
    ports:
      - 8080:8080

volumes:
  mongo_db: {} 



